from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent

CAMERA_SOURCE = str(PROJECT_ROOT / "videos" / "test.mp4")
MODEL_PATH = str(PROJECT_ROOT / "models" / "best.pt")

WINDOW_NAME = "SKYEYES"
CONFIDENCE = 0.4
YOLO_DEVICE = "cuda"
YOLO_IMAGE_SIZE = 640
YOLO_HALF = False
FRAME_WIDTH = 800
VIDEO_REALTIME_PLAYBACK = True
ARUCO_DICTIONARY = "DICT_4X4_50"
ALARM_COOLDOWN_SECONDS = 2.0
ESP32_ENABLED = False
ESP32_PORT = "COM3"
ESP32_BAUDRATE = 115200
TRACKING_MAX_DISTANCE = 80
TRACKING_MAX_MISSING = 10
STABILIZATION_ENABLED = False
STABILIZATION_MAX_FEATURES = 500
STABILIZATION_MIN_MATCHES = 12

BOUNDARY_POINTS = [
    (120, 120),
    (520, 120),
    (560, 420),
    (100, 420),
]
